<a href="https://colab.research.google.com/github/Adizcool/Room_Price_Prediction/blob/main/Room_Price_Prediction_Data_Preprocessing_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1) Install/ Import the required Python Packages/ Libraries**

In [1]:
#Import required python packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn import preprocessing
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
%matplotlib inline

**2) Mounting the Google Drive**

In [2]:
# Mount the Google Drive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


**3) Read the Data file and check**

In [3]:
# Read the Data from .csv file and check the data shape (number of Rows and Columns)
#df = pd.read_csv('gdrive/My Drive/Indi_ML_Training/Training-Sessions/MLP-Session25-05-Jun-2021/train_ctrUa4K.csv')
df = pd.read_csv("gdrive/My Drive/Datasets/Room Price Prediction/Room_Price_Data_Preprocessed.csv")
print(df.shape)
df.head()

(4201, 22)


CancellationPolicy  Accommodates  ...  PropertyType_3  PropertyType_4
0                   2             2  ...               0               1
1                   0             2  ...               0               1
2                   2             4  ...               0               1
3                   0             2  ...               0               1
4                   2             9  ...               0               1

[5 rows x 22 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4201 entries, 0 to 4200
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   CancellationPolicy  4201 non-null   int64  
 1   Accommodates        4201 non-null   int64  
 2   RoomType            4201 non-null   int64  
 3   Bathrooms           4201 non-null   float64
 4   Bedrooms            4201 non-null   float64
 5   CleaningFee         4201 non-null   float64
 6   ReviewRating        4201 non-null   float64
 7   Price               4201 non-null   float64
 8   District_Brooklyn   4201 non-null   int64  
 9   District_Manhattan  4201 non-null   int64  
 10  District_Queens     4201 non-null   int64  
 11  Neighborhood_0      4201 non-null   int64  
 12  Neighborhood_1      4201 non-null   int64  
 13  Neighborhood_2      4201 non-null   int64  
 14  Neighborhood_3      4201 non-null   int64  
 15  Neighborhood_4      4201 non-null   int64  
 16  Neighb

##**VII) Check the Test accuracy using appropriate algorithm and Holdout Method.**

##**Step-5: Slice X and y Values**

In [5]:
X = df.drop(['Price'], axis = 1)
Y = df['Price']
X.head()

CancellationPolicy  Accommodates  ...  PropertyType_3  PropertyType_4
0                   2             2  ...               0               1
1                   0             2  ...               0               1
2                   2             4  ...               0               1
3                   0             2  ...               0               1
4                   2             9  ...               0               1

[5 rows x 21 columns]

In [6]:
Y.head()

0    160.0
1    130.0
2    129.0
3    145.0
4    399.0
Name: Price, dtype: float64

##**Step-6: Execute Train-Test-Split Command and Verify**

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 66)

In [8]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(3360, 21)
(3360,)
(841, 21)
(841,)


In [9]:
alphas = [0.001, 0.01, 0.1, 1, 10]
print('All errors are RMSE')
print('-'*76)
for alpha in alphas:
    # instantiate and fit model
    ridge = Ridge(alpha=alpha, fit_intercept=True, random_state=99)
    ridge.fit(X_train, y_train)
    # calculate errors
    new_train_error1 = np.sqrt(mean_squared_error(y_train, ridge.predict(X_train)))
    #new_validation_error1 = np.sqrt(mean_squared_error(y_validation, ridge.predict(X_validation)))
    new_test_error1 = np.sqrt(mean_squared_error(y_test, ridge.predict(X_test)))
    # print errors as report
    #print('alpha: {:7} | train error: {:5} | val error: {:6} | test error: {}'.
    print('alpha: {:7} | train error: {:5} | test error: {}'.
          format(alpha,
                 round(new_train_error1,3),
                 #round(new_validation_error1,3),
                 round(new_test_error1,3)))

All errors are RMSE
----------------------------------------------------------------------------
alpha:   0.001 | train error: 69.766 | test error: 83.133
alpha:    0.01 | train error: 69.766 | test error: 83.133
alpha:     0.1 | train error: 69.766 | test error: 83.13
alpha:       1 | train error: 69.777 | test error: 83.122
alpha:      10 | train error: 69.845 | test error: 83.184


In [10]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=10)
ridge.fit(X_train, y_train) 
pred_train_ridge= ridge.predict(X_train)
Ridge_Train_Acc = r2_score(y_train, pred_train_ridge)
Ridge_Train_Err = np.sqrt(mean_squared_error(y_train,pred_train_ridge))
print("Train Error : ", np.sqrt(mean_squared_error(y_train,pred_train_ridge)))
print("Train Accuracy : ", r2_score(y_train, pred_train_ridge))
pred_test_ridge= ridge.predict(X_test)
Ridge_Test_Acc = r2_score(y_test, pred_test_ridge)
Ridge_Test_Err = np.sqrt(mean_squared_error(y_test,pred_test_ridge))
print("Test Error : ", np.sqrt(mean_squared_error(y_test,pred_test_ridge))) 
print("Test Accuracy : ", r2_score(y_test, pred_test_ridge))

Train Error :  69.84455345294701
Train Accuracy :  0.5711966807388652
Test Error :  83.18421980376996
Test Accuracy :  0.5500176409211615


In [11]:
# k-fold CV 
#lm = LinearRegression()
from sklearn.model_selection import cross_val_score
Ridge_scores = cross_val_score(ridge, X, Y, scoring='r2', cv=5)
print(Ridge_scores)
Ridge_CV_Average=np.average(Ridge_scores)   
Ridge_CV_Average

[0.57788548 0.508231   0.60235453 0.51940001 0.58849828]


0.5592738609848944

##**IX) Check for Multi-collinearity and find out the new accuracy as required**

###**Checking for MultiCollinearity**

VIF starts at 1 and has no upper limit

VIF = 1, no correlation between the independent variable and the other variables

VIF exceeding 5 or 10 indicates high multicollinearity between this independent variable and the others

In [12]:
# Import library for VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calc_vif(X):

    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return(vif)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [13]:
calc_vif(X)

variables         VIF
0   CancellationPolicy    3.841413
1         Accommodates    8.490512
2             RoomType    2.586458
3            Bathrooms   16.860029
4             Bedrooms    6.449313
5          CleaningFee    5.824447
6         ReviewRating  112.240090
7    District_Brooklyn    3.559062
8   District_Manhattan  200.393822
9      District_Queens    2.640803
10      Neighborhood_0    1.313444
11      Neighborhood_1    1.311056
12      Neighborhood_2    1.703973
13      Neighborhood_3    1.965582
14      Neighborhood_4    2.732606
15      Neighborhood_5    2.609807
16      PropertyType_0    1.021560
17      PropertyType_1    1.323844
18      PropertyType_2    1.919576
19      PropertyType_3    2.073189
20      PropertyType_4   81.291712

In [14]:
X.shape

(4201, 21)

In [15]:
X.columns

Index(['CancellationPolicy', 'Accommodates', 'RoomType', 'Bathrooms',
       'Bedrooms', 'CleaningFee', 'ReviewRating', 'District_Brooklyn',
       'District_Manhattan', 'District_Queens', 'Neighborhood_0',
       'Neighborhood_1', 'Neighborhood_2', 'Neighborhood_3', 'Neighborhood_4',
       'Neighborhood_5', 'PropertyType_0', 'PropertyType_1', 'PropertyType_2',
       'PropertyType_3', 'PropertyType_4'],
      dtype='object')

In [16]:
X1= X.drop(['Bathrooms', 'ReviewRating', 'District_Manhattan', 'PropertyType_4'], axis=1, inplace=False)

In [17]:
X1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4201 entries, 0 to 4200
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   CancellationPolicy  4201 non-null   int64  
 1   Accommodates        4201 non-null   int64  
 2   RoomType            4201 non-null   int64  
 3   Bedrooms            4201 non-null   float64
 4   CleaningFee         4201 non-null   float64
 5   District_Brooklyn   4201 non-null   int64  
 6   District_Queens     4201 non-null   int64  
 7   Neighborhood_0      4201 non-null   int64  
 8   Neighborhood_1      4201 non-null   int64  
 9   Neighborhood_2      4201 non-null   int64  
 10  Neighborhood_3      4201 non-null   int64  
 11  Neighborhood_4      4201 non-null   int64  
 12  Neighborhood_5      4201 non-null   int64  
 13  PropertyType_0      4201 non-null   int64  
 14  PropertyType_1      4201 non-null   int64  
 15  PropertyType_2      4201 non-null   int64  
 16  Proper

In [18]:
calc_vif(X1)

variables       VIF
0   CancellationPolicy  3.497181
1         Accommodates  7.463950
2             RoomType  2.032204
3             Bedrooms  6.292234
4          CleaningFee  4.876177
5    District_Brooklyn  1.178333
6      District_Queens  1.217919
7       Neighborhood_0  1.305506
8       Neighborhood_1  1.267123
9       Neighborhood_2  1.614065
10      Neighborhood_3  1.828161
11      Neighborhood_4  2.441553
12      Neighborhood_5  2.310222
13      PropertyType_0  1.001498
14      PropertyType_1  1.028418
15      PropertyType_2  1.224133
16      PropertyType_3  1.189725

In [19]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y, test_size = 0.2, random_state = 66)

In [20]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
model=regressor.fit(X1_train, Y1_train)

In [21]:
# Predicting the Test set results
Y1_pred = regressor.predict(X1_test)

In [22]:
print("Training Accuracy :", regressor.score(X1_train,Y1_train))
print("Testing Accuracy :", r2_score(Y1_test,Y1_pred))

Training Accuracy : 0.5477901175745981
Testing Accuracy : 0.5086402859176145


**Observation: After removal of the columns with IVF factor more than 10 " the model gives the accuracy less that of the accuracy without removal**

**Decision: We will not remove the columns**

##**X) Check for Outliers and handle them accordingly**

###**Outliers Detection**

In [23]:
df1=df

In [24]:
df1.head()

CancellationPolicy  Accommodates  ...  PropertyType_3  PropertyType_4
0                   2             2  ...               0               1
1                   0             2  ...               0               1
2                   2             4  ...               0               1
3                   0             2  ...               0               1
4                   2             9  ...               0               1

[5 rows x 22 columns]

In [25]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(df1))
print(z[:9])

[[8.35914827e-01 5.16540113e-01 8.33317804e-01 2.68780461e-01
  1.71669000e+00 2.48292321e-01 7.81732794e-01 1.21702988e-02
  1.09751038e-01 1.43704967e-01 8.89801462e-02 1.80815372e-01
  3.83241630e-01 7.73662739e-01 8.88359321e-01 1.20338489e+00
  8.45809694e-01 1.54303350e-02 9.55407383e-02 1.87720628e-01
  1.59324912e-01 2.10346352e-01]
 [1.62410492e+00 5.16540113e-01 8.33317804e-01 2.68780461e-01
  1.14928727e-01 2.07297133e-02 8.34495017e-01 2.84028285e-01
  1.09751038e-01 1.43704967e-01 8.89801462e-02 1.80815372e-01
  3.83241630e-01 7.73662739e-01 8.88359321e-01 8.30989326e-01
  1.18229905e+00 1.54303350e-02 9.55407383e-02 1.87720628e-01
  1.59324912e-01 2.10346352e-01]
 [8.35914827e-01 7.35253954e-01 8.33317804e-01 2.68780461e-01
  1.71669000e+00 8.48423073e-02 2.04508576e-01 2.93090218e-01
  1.09751038e-01 1.43704967e-01 8.89801462e-02 1.80815372e-01
  3.83241630e-01 7.73662739e-01 8.88359321e-01 8.30989326e-01
  8.45809694e-01 1.54303350e-02 9.55407383e-02 1.87720628e-01
  1.

In [26]:
z.shape

(4201, 22)

In [27]:
df2 = df1

In [28]:
threshold = 3
print(np.where(z > 3))

(array([   4,    4,    4, ..., 4188, 4197, 4197]), array([ 1,  3,  4, ..., 21,  4,  7]))


In [29]:
df2 = df2[(z < 3).all(axis=1)]

In [30]:
df2.shape

(3424, 22)

**Observation: Outliers are not observed in the given dataset**

**Decision: Hence no action needs to be taken**

##**XI) Check for Feature Selection/ Extraction and verify the accuracy**

###**Using Correlation Coefficient Method**

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4201 entries, 0 to 4200
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   CancellationPolicy  4201 non-null   int64  
 1   Accommodates        4201 non-null   int64  
 2   RoomType            4201 non-null   int64  
 3   Bathrooms           4201 non-null   float64
 4   Bedrooms            4201 non-null   float64
 5   CleaningFee         4201 non-null   float64
 6   ReviewRating        4201 non-null   float64
 7   Price               4201 non-null   float64
 8   District_Brooklyn   4201 non-null   int64  
 9   District_Manhattan  4201 non-null   int64  
 10  District_Queens     4201 non-null   int64  
 11  Neighborhood_0      4201 non-null   int64  
 12  Neighborhood_1      4201 non-null   int64  
 13  Neighborhood_2      4201 non-null   int64  
 14  Neighborhood_3      4201 non-null   int64  
 15  Neighborhood_4      4201 non-null   int64  
 16  Neighb

In [32]:
cor=df.corr()
cor

CancellationPolicy  ...  PropertyType_4
CancellationPolicy            1.000000  ...       -0.030479
Accommodates                  0.188786  ...       -0.079955
RoomType                     -0.118653  ...        0.002558
Bathrooms                     0.038530  ...       -0.039233
Bedrooms                      0.114281  ...       -0.066681
CleaningFee                   0.180883  ...       -0.085581
ReviewRating                 -0.007146  ...       -0.002684
Price                         0.149344  ...       -0.109164
District_Brooklyn            -0.040552  ...       -0.096781
District_Manhattan            0.025441  ...        0.137633
District_Queens               0.004732  ...       -0.101756
Neighborhood_0                0.000647  ...       -0.090201
Neighborhood_1               -0.010843  ...       -0.043160
Neighborhood_2               -0.000598  ...       -0.005740
Neighborhood_3               -0.002772  ...       -0.015439
Neighborhood_4               -0.007859  ...        0.065611
Neighborhood_5               -0.056803  ...        0.028200
PropertyType_0               -0.006081  ...       -0.073357
PropertyType_1               -0.000542  ...       -0.329390
PropertyType_2                0.045506  ...       -0.631758
PropertyType_3                0.038965  ...       -0.666177
PropertyType_4               -0.030479  ...        1.000000

[22 rows x 22 columns]

In [33]:
threshold=0.5
a = abs(cor['Price'])
a

CancellationPolicy    0.149344
Accommodates          0.567050
RoomType              0.506157
Bathrooms             0.350947
Bedrooms              0.419146
CleaningFee           0.535188
ReviewRating          0.075771
Price                 1.000000
District_Brooklyn     0.043207
District_Manhattan    0.075916
District_Queens       0.063415
Neighborhood_0        0.013310
Neighborhood_1        0.012191
Neighborhood_2        0.012977
Neighborhood_3        0.114426
Neighborhood_4        0.159732
Neighborhood_5        0.187150
PropertyType_0        0.004706
PropertyType_1        0.010525
PropertyType_2        0.121361
PropertyType_3        0.130043
PropertyType_4        0.109164
Name: Price, dtype: float64

In [34]:
result = a[a>0.5]
result

Accommodates    0.567050
RoomType        0.506157
CleaningFee     0.535188
Price           1.000000
Name: Price, dtype: float64

In [35]:
df.columns

Index(['CancellationPolicy', 'Accommodates', 'RoomType', 'Bathrooms',
       'Bedrooms', 'CleaningFee', 'ReviewRating', 'Price', 'District_Brooklyn',
       'District_Manhattan', 'District_Queens', 'Neighborhood_0',
       'Neighborhood_1', 'Neighborhood_2', 'Neighborhood_3', 'Neighborhood_4',
       'Neighborhood_5', 'PropertyType_0', 'PropertyType_1', 'PropertyType_2',
       'PropertyType_3', 'PropertyType_4'],
      dtype='object')

In [37]:
df4=df.drop(['CancellationPolicy', 'Bathrooms',
       'Bedrooms', 'ReviewRating', 'District_Brooklyn',
       'District_Manhattan', 'District_Queens', 'Neighborhood_0',
       'Neighborhood_1', 'Neighborhood_2', 'Neighborhood_3', 'Neighborhood_4',
       'Neighborhood_5', 'PropertyType_0', 'PropertyType_1',
       'PropertyType_2', 'PropertyType_3', 'PropertyType_4'], axis=1)
      

In [38]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4201 entries, 0 to 4200
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Accommodates  4201 non-null   int64  
 1   RoomType      4201 non-null   int64  
 2   CleaningFee   4201 non-null   float64
 3   Price         4201 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 131.4 KB


In [39]:
X5 = df4.drop(['Price'], axis = 1)
Y5 = df4['Price']
X5.head()

Accommodates  RoomType  CleaningFee
0             2         0    75.000000
1             2         0    66.646525
2             4         0    69.000000
3             2         0    60.000000
4             9         0   160.000000

In [40]:
Y5.head()

0    160.0
1    130.0
2    129.0
3    145.0
4    399.0
Name: Price, dtype: float64

In [41]:
from sklearn.model_selection import train_test_split
X5_train, X5_test, Y5_train, Y5_test = train_test_split(X5, Y5, test_size = 0.2, random_state = 66)

In [42]:
print(X5_train.shape)
print(Y5_train.shape)
print(X5_test.shape)
print(Y5_test.shape)

(3360, 3)
(3360,)
(841, 3)
(841,)


In [43]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
model=regressor.fit(X5_train, Y5_train)

In [44]:
# Predicting the Test set results
Y5_pred = regressor.predict(X5_test)

In [45]:
print("Training Accuracy :", regressor.score(X5_train,Y5_train))
print("Testing Accuracy :", r2_score(Y5_test,Y5_pred))

Training Accuracy : 0.47924452882518254
Testing Accuracy : 0.45234815089962377


**Observation: By dropping the columns based on feature selection the Test accuracy has not improved**

###**Decision: We will not go for feature selection.**


###**Applying PCA**

In [46]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X6_train = pca.fit_transform(X_train)
X6_test = pca.transform(X_test)
X6=pca.transform(X)
print(X6_train.shape)
print(X6_test.shape)
print(X6_train[:5])
print(Y[:5])

(3360, 2)
(841, 2)
[[  0.09659305  -6.31729348]
 [-36.5160015   -4.36185829]
 [-41.551138    -2.38235461]
 [  0.08711663  -4.32304239]
 [-46.55610208   3.61441   ]]
0    160.0
1    130.0
2    129.0
3    145.0
4    399.0
Name: Price, dtype: float64


In [47]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
model=regressor.fit(X6_train, y_train)

In [48]:
# Predicting the Test set results
Y6_pred = regressor.predict(X6_test)

In [49]:
print("Training Accuracy :", regressor.score(X6_train,y_train))
print("Testing Accuracy :", r2_score(y_test,Y6_pred))

Training Accuracy : 0.2890698859110624
Testing Accuracy : 0.2948886181474617


**Observation: By using the PCA Method, we did not get higher test accuracy**

###**Decision: We will not use the PCA Method for reducing the features**

###**Using LDA**

In [50]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)
X7_train = lda.fit_transform(X_train, y_train)
X7_test = lda.transform(X_test)
X7=lda.transform(X)
print(X7_train[:5])
print()
print(X7_test[:5])

[[1.46544092]
 [0.01471832]
 [1.46918822]
 [0.94497944]
 [1.58070422]]

[[ 1.52556842]
 [ 0.07278114]
 [-0.863027  ]
 [ 2.43869592]
 [-0.29654171]]


In [51]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
model=regressor.fit(X7_train, y_train)

In [52]:
# Predicting the Test set results
Y7_pred = regressor.predict(X7_test)

In [53]:
print("Training Accuracy :", regressor.score(X7_train,y_train))
print("Testing Accuracy :", r2_score(y_test,Y7_pred))

Training Accuracy : 0.5527096237964237
Testing Accuracy : 0.5252922808311118


**Observation: By using the LDA Method the testing accuracy is not improved**

###**Decision: We will not use the LDA Method for reducing the features**